#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx
./1-install_nginx_web_server > /dev/null 2>&1
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
